#!/bin/bash

# generated by chatgpt

# Check if virtual environment exists, and create one if not
if [ ! -d "env" ]
then
    echo "Virtual environment not found, creating one..."
    python3.11 -m venv env
    INSTALL=true
fi

# Parse command line arguments
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --install)
            INSTALL=true
            shift # past argument
            ;;
        *)    # unknown option
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Activate virtual environment
source env/bin/activate

# Install requirements if requested
if [ "$INSTALL" = true ]; then
    python3 -m pip install -r requirements.txt
    pip install --upgrade pip
fi

exec $SHELL
